version: '3.9'

volumes:
  postgres-data:
    external: false # Внешние волюмы не привязываются к композу и при docker-compose down --volumes не удаляются
  redis-data:
    external: false

networks:
  litminka-net: 
    external: false

services:
  postgre-db:
    container_name: litminer-db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "litminer"
      POSTGRES_USER: "arckontyr"
      POSTGRES_PASSWORD: "arc"
    ports:
      - target: 5432
        published: 5434
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - litminka-net

  redis:
    container_name: litminer-redis
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    ports:
      - target: 6379
        published: 6380
    networks:
      - litminka-net
  
  lavalink:
    container_name: lavalink
    image: ghcr.io/lavalink-devs/lavalink:4
    environment:
      _JAVA_OPTIONS: -Xmx2G
      SERVER_PORT: 2333
      LAVALINK_SERVER_PASSWORD: "lava"
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins/:/opt/Lavalink/plugins/
    networks: 
      - litminka-net
    expose: 
      - 2333
    ports: 
      - "2333:2333"
